### ISSUE TITLE
dialog altta görünüyor.

### ISSUE THREAD

**Issue by receptuna** [volkanceylan/Serene#1]
![image](https://cloud.githubusercontent.com/assets/2880274/11454360/f70b3500-9631-11e5-8ef0-8281a0f4ad80.png)

@volkanceylan acaba genl bir sıkıntı mıdır ? dialog açınca menu ve header aktmanlarının altında görünüyor.

İyi geceler.

**Comment by volkanceylan** [comment]
adminlte less teki z-order ile alakalı override ları uygula

29 Kasım 2015 00:43 tarihinde receptuna <notifications@github.com> yazdı:

**Comment by volkanceylan** [comment]
.ui-front {
    z-index: 1100;
}

bu da olur

29 Kasım 2015 00:59 tarihinde Volkan Ceylan <volkanceylan@gmail.com> yazdı:

**Comment by receptuna** [comment]
Tamamdır @volkanceylan sorun çözülmüştür.

Teşekkür ederim.
