### ISSUE TITLE
 Serene/Serene/Serene.Web/App_Start/SiteInitialization.Migrations.cs 

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serene#10]
```
var isLocalServer = serverConnection.ConnectionString.IndexOf(@"(localdb)\", StringComparison.OrdinalIgnoreCase) >= 0 ||
                    serverConnection.ConnectionString.IndexOf(@".\") >= 0;

                string command;
                if (isLocalServer)
                {
                    var filename = Path.Combine(HostingEnvironment.MapPath("~/App_Data"), catalog);
                    command = String.Format(@"CREATE DATABASE [{0}] ON PRIMARY (Name = N'{0}', FILENAME = '{1}.mdf') LOG ON (NAME = N'{0}_log', FILENAME = '{1}.ldf')",
                        catalog, filename);

                    if (File.Exists(filename + ".mdf"))
                        command += " FOR ATTACH";
                }
                else
                {
                    command = String.Format(createDatabaseQuery, catalog);
                }
```
causes a fallover if you use:
```
<add name="Default" connectionString="Data Source=.\SqlExpress; 
        Initial Catalog=Serene_Default_v1; Integrated Security=True"
        providerName="System.Data.SqlClient" />
```
The issue is that the connection string for SQLExpress passes through the filename check. It's a local server but not a file so that needs to pass to the else condition.

**Comment by volkanceylan** [comment]
I'm not sure if it is a problem. Can't we specify file location for SQL express also, just like local sql server or local db. This is to create database under App_Data for local server types.

**Comment by solabar** [comment]
Express runs as a regular SQL server. I did a workaround for my own version just removing the || condition of the if.
SQLExpress is a local SQL install but not a local file IIRC. Not very breaking an issue as it's a quick fix to change it but I thought you might like to know.

Perhaps adding:
```
if (isLocalServer)
                {
                    if (serverConnection.ConnectionString.Contains("SQLEXPRESS")) { isLocalServer = false; }
                }
```

**Comment by volkanceylan** [comment]
I know, but SQL express should let you specify database location, why you are getting an error? Maybe because you already have local db database under app_data

**Comment by volkanceylan** [comment]
I mean Serene_Default_v1.mdb file that was already attached to (localdb)

**Comment by solabar** [comment]
Whats happening is that if you connection string is .\SLQEXPRESS the. is picked up by the if. Then it drops you into creating a query with a filename in the path. That drops you into an error. Does that make sense?

**Comment by volkanceylan** [comment]
Solabar, what i mean is this was by design. I put ".\" there specially to catch SQL express. SQL express lets you create database files in a location you choose, just like SQL local db. You are getting error because another database that is attached to local db at same location, and it is locked. Anyway nevermind, you found the solution.
