### ISSUE TITLE
Support for ASP.Net Bundling?

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serene#15]
Serenity does not currently support ASP.Net Bundling because Url references in CSS which assume a relative folder structure are no longer valid once the CSS is bundled. I've fixed all the references in my project and am happy to share, but the changes look like this:
`background-image: url(images/cross.png);`
becomes
`background-image: url(/Content/serenity/images/cross.png);`

That might restrict the hosting environment a bit, I don't know.

When bundled, my site's footprint shrinks from 67 requests at 3.5MB to 17 requests at 2MB. Ideally I'd like to see that under 1MB but given the awesome functionality in Serene, I doubt I'll be able to get it quite that small :-)

**Comment by wldkrd1** [comment]
Actually, I have a better solution. CssRewriteUrlTransform() will take care of it automatically.
```
var styBundle = new StyleBundle("~/Content/bundle").Include(
                "~/Content/site/site.css", new CssRewriteUrlTransform());
```

**Comment by volkanceylan** [comment]
Serenity has a bundling system actually just not minification, for which i use uglifyjs and clean css. Currently i run these two at deployment script, using nodejs thats why i didnt put a sample yet. CleanCSS can handle relative paths pretty easy.

**Comment by volkanceylan** [comment]
Btw minified m gzipped it should be under 500 kb, excluding images and some optionals like CKEditor
