### ISSUE TITLE
Sing Up validation issues (serene {2.1.5})

### ISSUE THREAD

**Issue by awesomegithubusername** [volkanceylan/Serene#17]
Hi;

Email and Password validation in sign up form doesn't seem to be working ({2.1.5}) :

![serenetypescript](https://cloud.githubusercontent.com/assets/13295503/15294834/bfa817fc-1b85-11e6-81c8-1b3141e8db95.png)

**Comment by volkanceylan** [comment]
AddValidationRule in general is not working at all since 2.1.3. Typo in TypeScript conversion. Fixed in 2.1.6

**Comment by awesomegithubusername** [comment]
Thanks volkan. It's working now.
