### ISSUE TITLE
Add a chapter to Serenity Guide

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serene#2]
Hi, 
You have really done a awesome platform to work with.

Can you please add a chapter that describes how it works. 

For example: I am not able to find out the view code. How this platform generates views and how can I modify them. Explain please. 

Thanks in advanced.

**Comment by VictorTomaili** [comment]
Views looks like [CustomerIndex.cshtml](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Customer/CustomerIndex.cshtml#L10). Its include a initial javascript inside. This javascript init the [CustomerGrid.cs](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Script/Northwind/Customer/CustomerGrid.cs) script class. That class inherrit `EntityGrid<[TypeOfRow]>` and interface `IAsyncIni` for generate grid. 

[CustomerPage.cs](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Customer/CustomerPage.cs) is page class what pointed `CustomerIndex.cshtml`. [This](https://github.com/volkanceylan/Serene/blob/c2afdbe0b2f29d8b9be96c2cab03aeb916c55ce6/Serene/Serene.Web/Modules/Common/MVC/MVC.cs#L139) class has constant paths for intellisense support. 

[Navigation configurations](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Common/Navigation/NavigationItems.cs#L8) has global attributes for pointing menu and page file.

If you want to modify layout without grid, you can use panel instead grid for init from view.

**Comment by dfaruque** [comment]
Thank you, 
What about form generation.

**Comment by VictorTomaili** [comment]
Hi again,

Forms are generated hierarchical based rows. Its mean forms are override row properties. If row has a string property, its mean forms are use `StringEditor`. But you can also override it with `NumberEditor`. 
[CustomerForm.cs](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Web/Modules/Northwind/Customer/CustomerForm.cs) is server side descriptions for forms and define editor types. An dynamic script generated from this form class what called from [CustomerDialog.cs](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Script/Northwind/Customer/CustomerDialog.cs). 

When you want to accessing this form from the script side, There is easy way. [OrderDialog.cs](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Script/Northwind/Order/OrderDialog.cs#L15) has a form description for customizing form elements. [OrderForm](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Script/Imports/FormContexts/Northwind.OrderForm.cs) generated automatically by Script side TextTemplate file. It's read web project assembly and find `OrderForm` class for generation. And you can manage html element in `OrderDialog` with use this variable. 

Dialogs are called from grids. Grids has default buttons like create new row item or refresh grid. If you want to add new button [there](https://github.com/volkanceylan/Serene/blob/master/Serene/Serene.Script/Northwind/Customer/CustomerGrid.cs#L31) is sample of creating button.

Also dont forget serenity has a code generator for this. Try to run `sergen` from visual studio command window. Its call a code generator what installed from nuget. You can select table what you want to use and other properties. This application generates all this codes for you. And you only need to edit this code for your wants.

**Comment by VictorTomaili** [comment]
Last one, try to ask this questions to under `https://github.com/volkanceylan/Serenity` its has more follower for helping.

**Comment by dfaruque** [comment]
Thanks again. 

One more thing, if I want to add an event handler to forms elements than what to do.

**Comment by VictorTomaili** [comment]
Its looks like cascaded editors. But using using text editor. [How To: Setup Cascaded Editors](https://volkanceylan.gitbooks.io/serenity-guide/content/howto/how_to_setup_cascaded_editors.html)

**Comment by volkanceylan** [comment]
form.MyElement.Change(...)

**Comment by VictorTomaili** [comment]
ohh sorry, i remembered old version of cascaded editors what changed by manually :smile:

**Comment by dfaruque** [comment]
where should I put form.MyElement.Change(...);

**Comment by volkanceylan** [comment]
In YourDialog.cs. See OrderDetailDialog.

**Comment by dfaruque** [comment]
Thanks. got it.
