### ISSUE TITLE
how can I use serene in an empty asp.net mvc project

### ISSUE THREAD

**Issue by ragoob** [volkanceylan/Serene#7]

**Comment by volkanceylan** [comment]
You can but it will be a lot of manual work. It is better to start with a new Serene project, than remove Northwind etc. following guide.

Anyway if you are desperate, create empty ASP.NET project, and one for Saltarelle scripts, and start adding relevant Serenity Nuget packages to your projects.

**Comment by ragoob** [comment]
the reason of starting without  Serene project is i have an exists  database 
with asp identity membership if you can help me to working with Serene project template 
without Northwind  and  Serene  database I will be very grateful to you

**Comment by volkanceylan** [comment]
Serene works with any membership, just implement and register IPermissionService, IAuthorizationService etc. Information exists in guide.

**Comment by volkanceylan** [comment]
@ragoob see how another user merged Serenity with Asp.net membership here:

https://github.com/volkanceylan/Serenity/issues/382
