### ISSUE TITLE
slick grid grouping : Slick grid üzerinde gruplama enum field üzerinden yapılınca enumun integer değeri görünüyor

### ISSUE THREAD

**Issue by receptuna** [volkanceylan/Serene#8]
Selam @volkanceylan 

Slick grid üzerinde gruplama enum field üzerinden yapılınca enumun integer değeri görünüyor

![image](https://cloud.githubusercontent.com/assets/2880274/13812743/8a988198-eb86-11e5-923d-e4ae3294ed8b.png)

İyi çalışmalar.

**Comment by volkanceylan** [comment]
GroupFormatter parametresini  vermen lazım kolonda

**Comment by receptuna** [comment]
tamam teşekkür ederim @volkanceylan iyi çalışmalar.

**Comment by receptuna** [comment]
`Formatter = x => EnumFormatter.Format(typeof(EnumType), x.Value)` 
ok
