### ISSUE TITLE
fastclick.min.js IE Interaction

### ISSUE THREAD

**Issue by solabar** [volkanceylan/Serene#9]
fastclick.min.js throws errors on document.dispatchEvent(new CustomEvent('o.DOMContentLoaded')) 
I know this isn't part of serene but part of AdminLTE, but I would suggest this get removed from the Serene template as it's a breaking issue on Sliders for IE. Especially as fastclick appears to be a dead repository now. This issue has been around since 2015.

**Comment by volkanceylan** [comment]
Isnt it required for AdminLTE nav or demo pages?

**Comment by solabar** [comment]
Looks like it is just on the sliders. That's the only thing that seems to throw an error.

**Comment by solabar** [comment]
I wonder if I can raise this on AdminLTE and see if they can hack it in their template. I will try that too. Just wanted to make sure you knew there was an issue.

**Comment by volkanceylan** [comment]
Ok thanks i'll also have a look, is it IE or Edge it is failing? Which version?

**Comment by solabar** [comment]
IE 11.
Taking a look at AdminLTE directly it looks like the newest version they have solves the problem. Might be worth updating the template section to use the new source? Perhaps that is quickest. I am going to work with my local version to see what I can do here.

**Comment by solabar** [comment]
Found the issue for definate. If you use  fastclick/lib/fastclick.js in place of the version we have right now it functions when you minimize

**Comment by volkanceylan** [comment]
I removed fastclick.min.js but couldn't see the problem in IE 11 either. But there are some reports about fastclick.min.js.
